name: Build and push CI

on:
  push:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-20.04
    env:
      REPOSITORY_PREFIX: "${{ secrets.DOCKER_HUB_USER }}"
      PATHS: spring-petclinic-customers-service spring-petclinic-vets-service spring-petclinic-visits-service
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build image of customers service
      working-directory: ./spring-petclinic-cloud
      run: for p in ${{ env.PATHS }}; do cd $p && mvn spring-boot:build-image -Pk8s -DREPOSITORY_PREFIX=${{ env.REPOSITORY_PREFIX }} && cd ..; done 
    - name: Push images
      run: for p in ${{ env.PATHS }}; do echo ${p} && docker push ${{ env.REPOSITORY_PREFIX }}/${p}:latest; done
