name: Docker Image CI

on:
  push:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-20.04
    env:
      REPOSITORY_PREFIX: "${{ secrets.DOCKER_HUB_USER }}/wus/petclinic"
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build image of customers service
      working-directory: ./spring-petclinic-cloud/spring-petclinic-customers-service
      run: mvn spring-boot:build-image -Pk8s -DREPOSITORY_PREFIX=${{ env.REPOSITORY_PREFIX }} && docker push ${{ env.REPOSITORY_PREFIX }}/spring-petclinic-cloud-customers-service:latest
