name: Build and push CI

on:
  push:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-20.04
    env:
      REPOSITORY_PREFIX: "${{ secrets.DOCKER_HUB_USER }}"
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build image of customers service
      working-directory: ./spring-petclinic-cloud/spring-petclinic-customers-service
      run: mvn spring-boot:build-image -Pk8s -DREPOSITORY_PREFIX=${{ env.REPOSITORY_PREFIX }}
    - name: Push images
      run: docker push ${{ env.REPOSITORY_PREFIX }}/spring-petclinic-cloud-customers-service:latest
