name: Build and push CI

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      REPOSITORY_PREFIX: "${{ secrets.DOCKER_HUB_USER }}"
      PATHS: customers-service vets-service visits-service
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build images
      working-directory: ./spring-petclinic-cloud
      run: for p in ${{ env.PATHS }}; do cd "spring-petclinic-${p}" && mvn spring-boot:build-image -Pk8s -DREPOSITORY_PREFIX=${{ env.REPOSITORY_PREFIX }} && cd ..; done 
    - name: List images
      run: docker images
    - name: Push images
      run: for p in ${{ env.PATHS }}; do docker push "${{ env.REPOSITORY_PREFIX }}/spring-petclinic-cloud-${p}:latest"; done
  deploy:
      needs: [build]
      runs-on: ubuntu-20.04
      env:
        REPOSITORY_PREFIX: "${{ secrets.DOCKER_HUB_USER }}"
        PATHS: customers-service vets-service visits-service
      steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      - name: Build images
        working-directory: ./spring-petclinic-cloud
        run: chmod +x scripts/deployToKubernetes.sh && ./scripts/deployToKubernetes.sh